### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by cboden** [riiid/rxjs-dash#4]
> bower@1.7.2 node_modules/bower
└── semver-utils@1.1.1
TypeError: Object #<Object> has no method 'parse'
  at /rxjs-dash/docset.coffee:158:33
  at tryCatcher (/rxjs-dash/node_modules/rx/dist/rx.js:63:31)
  at InnerObserver.Rx.FlatMapObservable.InnerObserver.next (/rxjs-dash/node_modules/rx/dist/rx.js:2130:43)
  at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/rxjs-dash/node_modules/rx/dist/rx.js:1752:31)
  at InnerObserver.tryCatcher (/rxjs-dash/node_modules/rx/dist/rx.js:63:31)
  at AutoDetachObserverPrototype.next (/rxjs-dash/node_modules/rx/dist/rx.js:5747:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/rxjs-dash/node_modules/rx/dist/rx.js:1752:31)
  at loopRecursive (/rxjs-dash/node_modules/rx/dist/rx.js:2794:13)
  at [object Object].invokeRecImmediate [as action] (/rxjs-dash/node_modules/rx/dist/rx.js:967:7)
  at [object Object].ScheduledItem.invokeCore (/rxjs-dash/node_modules/rx/dist/rx.js:896:33)
  at [object Object].ScheduledItem.invoke (/rxjs-dash/node_modules/rx/dist/rx.js:884:40)
  at runTrampoline (/rxjs-dash/node_modules/rx/dist/rx.js:1125:37)
  at tryCatcher (/rxjs-dash/node_modules/rx/dist/rx.js:63:31)
  at CurrentThreadScheduler.schedule (/rxjs-dash/node_modules/rx/dist/rx.js:1141:45)
  at EveryObservable.Rx.ObservableBase.ObservableBase._subscribe (/rxjs-dash/node_modules/rx/dist/rx.js:2085:32)
  at EveryObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (/rxjs-dash/node_modules/rx/dist/rx.js:2024:19)
  at Object.<anonymous> (/rxjs-dash/docset.coffee:166:4)
  at Object.<anonymous> (/rxjs-dash/docset.coffee:1:1)
  at Module._compile (module.js:456:26)

I've downloaded the latest build to get it in my Dash temporarily. Also the package in Dash is called "rsjx" instead of "RxJS".

**Comment by chitacan** [comment]
Which version of node did you run? you should use `>=0.12` to use `path.parse`.
(sorry that I did not specify node version on `package.json` :sweat: )
